version: '3.1'

services:  

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Abc12345
      MYSQL_DATABASE: dev_db
    ports:
      - "3307:3306"
    volumes:
      - $HOME/dev/business-api/mysql.sql:/mysql.sql